### ISSUE TITLE
Gazebo does not recognize quadrotor model

### ISSUE THREAD

**Issue by michellieo** [rumaisaabdulhai/quad_sim#1]
Gazebo does not recognize the quad model, instead of the quadrotor, it appears a cube. I have attached the terminal error and the Gazebo screenshot.
![WhatsApp Image 2020-10-08 at 9 58 24 AM](https://user-images.githubusercontent.com/55675882/95545418-728c4480-09c3-11eb-9049-8e760c642511.jpeg)
![WhatsApp Image 2020-10-08 at 9 46 00 AM](https://user-images.githubusercontent.com/55675882/95545423-74ee9e80-09c3-11eb-9342-1580c56107a1.jpeg)

**Comment by rumaisaabdulhai** [comment]
Hello,

The issue seems to be that there was already a quadrotor spawned in the environment before the gazebo service tried to add one. I would check the `schools.world` file in the `quadcopter_gazebo` package and remove any quadrotor models that exist there.

I pushed out the updated code a few hours ago with this bug fixed, so you can either reclone/redownload the repository or pull by typing "git pull" in the repository directory. Let me know if this works.
